### ISSUE TITLE
Collect superscript and subscript texts from figma

### ISSUE THREAD

**Issue by KevynTD** [bernaferrari/FigmaToCode#103]
Your extension is very good, thank you btw!!

In figma, the designers on my team use this functionality a lot to place the text with sub or sup text, but when I copy the text of it, it never works:
<img width="249" alt="image" src="https://github.com/bernaferrari/FigmaToCode/assets/44689444/881c07d4-f5cd-414f-ac49-b688020f089b">

If you could export this on HTML, it would be amazing not to have to do the manual work of placing each of these by hand 😅

In HTML the tags used for this are [&lt;sub>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub) and [&lt;sup>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup), and in CSS, the equivalent is to use the "[vertical-align](https://developer.mozilla.org/pt-BR/docs/Web/CSS/vertical-align): sub;font-size: 0.9em;" and "[vertical-align](https://developer.mozilla.org/pt-BR/docs/Web/CSS/vertical-align): super;font-size: 0.9em;" respectively.

**Comment by bernaferrari** [comment]
hmmm, maybe I can do that? Can you share a simple Figma layout of what you want? I'll take a look if it is possible to do what you want. If it is, I'll surely do it.

**Comment by KevynTDGlobant** [comment]
Apologies for the delay!
I made a very simple example in this file, I'm new to creating things in figma
In this file I put some examples of how I would like the text to be exported
[Sup and Sub Text Examples.zip](https://github.com/user-attachments/files/15877776/Sup.and.Sub.Text.Examples.zip)

![image](https://github.com/bernaferrari/FigmaToCode/assets/148471318/e97e555a-8c6d-4be9-be9b-7aa7bbefb440)

In the current export to html, the numbers and letters with sup/sub remain as normal text

**Comment by KevynTD** [comment]
Apologies for the delay!
I made a very simple example in this file, I'm new to creating things in figma
In this file I put some examples of how I would like the text to be exported
[Sup and Sub Text Examples.zip](https://github.com/user-attachments/files/15877776/Sup.and.Sub.Text.Examples.zip)

![image](https://github.com/bernaferrari/FigmaToCode/assets/148471318/e97e555a-8c6d-4be9-be9b-7aa7bbefb440)

In the current export to html, the numbers and letters with sup/sub remain as normal text

**Comment by KevynTD** [comment]
Hello @bernaferrari!
I have some news

I dug into your code a bit and started researching the topic of Figma plugins
And I saw that the official documentation didn't have anything to get Sub and Sup from the text (in these words at least).

I opened a ticket to the Figma Team, asking them to add this method to getStyledTextSegments (which is what I saw you use here), they said it already exists, and can be used as `node.getStyledTextSegments(['openTypeFeatures'])`, so I asked them to update the documentation, since this wasn't written in the [getStyledTextSegments](https://www.figma.com/plugin-docs/api/properties/TextNode-getstyledtextsegments/) documentation.

I did a quick console.log test, and it worked to extract Sub and Sup:
![image](https://github.com/user-attachments/assets/7ae490b8-3b19-4441-a675-804643e7615f)
![image](https://github.com/user-attachments/assets/220df86b-c99e-4329-92c1-d75a91f85a20)



I'm not that experienced in your code yet, but I think this might help something.

**Comment by bernaferrari** [comment]
oh, I completely forgot that. I'll get that working, thanks!!

**Comment by pulonaglobant** [comment]
@bernaferrari I also would have great usage on my daily tasks for this feature (meaning the sup/sub - we work with a lot of references using <sup> and molecules having <sub> texts), it would be amazing if you'd add that. I'd like to thank you in any case for the plugin, it speeds up a whole lot of things.

**Comment by bernaferrari** [comment]
I'll get this done by the end of this week!

**Comment by pulonaglobant** [comment]
> I'll get this done by the end of this week!

that's amazing news dude. thanks for the hard work, really appreciate it

**Comment by bernaferrari** [comment]
Finally, thanks for the patience. Fixed and deployed!!

**Comment by pulonaglobant** [comment]
> Finally, thanks for the patience. Fixed and deployed!!

you're the best dude, thanks a lot!
