### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by FatSandwich** [bernaferrari/FigmaToCode#12]
I love this tool so much! But, is there a way to add positioning like X and Y? I'm not very good with HStacks, ZStacks, and VStacks so that would be a great feature!

**Comment by bernaferrari** [comment]
Well.. I guess you don't like that I use `offset` with ZStack and you wish I would use `position`? HStack and VStack are just horizontal and vertical stacks, and are extremely useful for building responsive apps. You should only use absolute position in some custom views or determined situations, but most of your app should rely in other types.

**Comment by FatSandwich** [comment]
Ok, thanks!
