### ISSUE TITLE
TurboRepo build commands don't work, docs out of date

### ISSUE THREAD

**Issue by mimshwright** [bernaferrari/FigmaToCode#127]
Hi. I'm new to this project and am trying to get it to build but having issues. 

The README seems to be out of date as it mentions Webpack and Rollup which don't seem to be here now. 

I tried running `pnpm dev` and found the following issues which I fixed as I went:
- missing packageManager field in package.json
- changed in 2.0: `pipeline` has been renamed to `tasks`
- could not find task `dev` in project
- could not find task `build:watch` in project

`pnpm build` did partially work but:
- I needed to upgrade node to >v18.17.0 (would be nice to have a note about this)
- ESLint: Invalid Options: - Unknown options: useEslintrc, extensions - 'extensions' has been removed.

I was eventually able to see a debug mode using `dev` after creating a new `dev` task in turbo.json. 

Is it possible that some of your files, especially turbo.json, didn't get committed to main?

**Comment by mimshwright** [comment]
Related: #79

**Comment by bernaferrari** [comment]
Some things changed :(
I'll update for you, but you are on the correct way, it is basically just fixing these deprecation errors and possibly updating the dependencies again.

**Comment by mimshwright** [comment]
Thanks for the fast response! if you can double check that turbo.json is up to date, that is probably all i need. Once i have it working, i do a PR for this.

**Comment by mimshwright** [comment]
At some point I built `debug` but later couldn't figure out how I did it 😓  Could you add a note about that?

**Comment by bernaferrari** [comment]
Usually it is turbo dev, but I do the plugin only from its dir.

**Comment by mimshwright** [comment]
added a small change to mention the debug mode.
