### ISSUE TITLE
__tests__ no longer used?

### ISSUE THREAD

**Issue by mimshwright** [bernaferrari/FigmaToCode#136]
It seems like __tests__, which contains jest tests, is no longer used. Is that right?
It seems like it still could be useful to run unit tests on backend code even if there's a new debug mode for UI elements. 

Can it and jest stuff be deleted?

**Comment by bernaferrari** [comment]
Yep, it can be deleted. They were used in the older version (a lot!) but it became too hard to maintain them, I gave up.

**Comment by mimshwright** [comment]
Fixed by #141
