### ISSUE TITLE
Basic usage manual

### ISSUE THREAD

**Issue by mlnmln** [bernaferrari/FigmaToCode#18]
Forgive my ignorance, not super familiar with Figma plugins. 

I don't unterstand how to run this plugin. 

1. Installed the plugin 
2. Plugin is listed on manage plugins
3. Plugin is not listed anywhere else in Figma as far as I have seen. 
3. x Don't get how to display the Figma To Code window as displayed in introduction video in the readme

Alternate path:

1. Checked out the repo
2. npm install, npm run build, npm run start
3. working local server with a web ui similar to the Figma To Code window at localhost:5000
4. x No connection to Figma whatsoever. 

I have the feeling I'm missing something super obvious here. :) 

Appreciate your help/feedback!

**Comment by bernaferrari** [comment]
Hey. If you installed it, it should work just like any other plugin. Open a
project, right click in the canvas, look for plugins (should be one of the
last options) and there it shows the list.

You can see here for better instructions:

https://help.figma.com/hc/en-us/articles/360042532714-Use-Plugins-in-the-Editor

Does that help?

**Comment by mlnmln** [comment]
Yes, it does! Thank you so much! 

>  Users with Edit access to a File can run a plugin in that File.

The key was, that I was trying to run this in a file where I did not have edit rights. When I create a file of my own, everything works as expected. Awesome.

**Comment by bernaferrari** [comment]
You are welcome!
