### ISSUE TITLE
A bug of primaryAlign when primaryAxisAlignItems = SPACE_BETWEEN

### ISSUE THREAD

**Issue by oney** [bernaferrari/FigmaToCode#22]
https://github.com/bernaferrari/FigmaToCode/blob/ae47851096afafbd1c21bab34149f6dbdad7b2f8/src/html/htmlMain.ts#L244
This gives `justify-content: justify-between;`, but there is no `justify-between` I think.
`primaryAlign = "space-between";` should fix it.

Also, it's further better if not inserting `<div style="width: --px"></div>` empty div between real items when `primaryAxisAlignItems = SPACE_BETWEEN` because flexbox will handle that.

However, `space-between` still causes a problem for one single item in parent div. See [this](https://stackoverflow.com/questions/57859754/flexbox-space-between-but-center-if-one-element).
I don't like `margin: 0 auto;` solution.
One solution may be if there is only 1 item in the parent div, use `center` rather than `space-between`.(but it doesn't work for dynamic children)

Please let me know if you need examples to demonstrate this.
Thanks a lot for this project!

**Comment by bernaferrari** [comment]
> there is no justify-between I think
You are right. It came from Tailwind. Fixed!

> it's further better if not inserting
That makes sense! Added an exception for this, it will now center.

Thanks!
