### ISSUE TITLE
Text and Corner radius bugs

### ISSUE THREAD

**Issue by oney** [bernaferrari/FigmaToCode#24]
## 1
Text elements under auto layout parent with "Fill container" width doesn't have `width: 100%` in generated codes.
## 2
Corner radius in Figma doesn't produce `border-radius:` in generated codes.
## 3
Text's color generates something like`<p class="Location" style="font-size: 11.50px; text: rgba(37.78, 188.06, 13.32, 1);">Text</p>`. It should be `color: rgba(37.78, 188.06, 13.32, 1);`
## 4
In auto layout, the bottom empty spacing div's height of a Text should = parent's spacing + Text's height - Text's font size to be more accurate.

**Comment by bernaferrari** [comment]
Awesome feedback, I'll fix them!

**Comment by bernaferrari** [comment]
Ok, I have fixed 1, 2 and 3 already (landing in Figma soon, as soon as I fix the others).

I don't understand 4. Is this difference what you mean?
![image](https://user-images.githubusercontent.com/351125/107124067-4f45a900-6880-11eb-8ea8-be47f8ce9711.png)

**Comment by oney** [comment]
Never mind for 4.
When line height is auto in Figma, the generated CSS won't have `line-height`. This makes inconsistency in look.
So inconsistency can be fixed by manually setting the line height to be a value in Figma.

**Comment by bernaferrari** [comment]
I fix it, but only for HTML. HTML supports height 100%.
