### ISSUE TITLE
placeholder problems

### ISSUE THREAD

**Issue by tonyrewin** [bernaferrari/FigmaToCode#38]
`
<img class="flex flex-col items-end justify-start w-full flex-1 p-2" src="https://via.placeholder.com/380x300">
 <img class="w-8 h-8 rounded-lg" src="https://via.placeholder.com/32.000030517578125x32"/>
</img>
`

the only markup problem I found in generated code is these two:
- size is better to be int
- no img inside img, please

**Comment by bernaferrari** [comment]
wow, thanks!

No img inside img is tricky, because in Figma the images can be inside an image...

**Comment by Anshika91** [comment]
Hey pls assign this task to me

**Comment by bernaferrari** [comment]
> size is better to be int

fixed (has been fixed for more than a year)

> no img inside img

fixed too (was fixed last year I believe)
