### ISSUE TITLE
Add option to prettify the code (i.e. nice indents)

### ISSUE THREAD

**Issue by TanayB11** [bernaferrari/FigmaToCode#4]
This plugin is amazing, I love it!

I tried using it to add in some HTML for me with Tailwind, and the output for the plugin is mostly minified. I have to then go back into the code and then format it. Ideally, there should be an option to deliver the output for Tailwind in a way that is more readable.

**Comment by bernaferrari** [comment]
I agree. However, you can access prettify tools very easy, on both vscode and codepen. It is supposed to be just a click (or shortcut) away. Can you give me a scenario where you don't have access to these tools?

**Comment by TanayB11** [comment]
It would be nicer to have it built into the tool mainly to inspect what is going on. For larger (or smaller) HTML outputs, often a user might want to inspect what is coming out to see what they might want to tweak, add, or remove.

I use Vim and haven't figured out how to get that to work yet (I'm certain there's a way, so it's not worth adding it just for that reason).

**Comment by bernaferrari** [comment]
The biggest issue is that I append the values to the end of the string, and sometimes use "\n", but it doesn't keep track of indentation. So I would need to keep track and then add the correct number of spaces for every newline..

You could also try this extension: https://github.com/prettier/vim-prettier

**Comment by TanayB11** [comment]
You're right, and it doesn't seem to be worth the effort at this point. Now that I've had some time to think about it, it might just be a better idea to leave it to the editor.

**Comment by bernaferrari** [comment]
Thanks! haha
Yeah, ideally everybody should be using prettifier or something else. That might be a way to enforce those good practices 😛
