### ISSUE TITLE
Code for images

### ISSUE THREAD

**Issue by michael4reynolds** [bernaferrari/FigmaToCode#7]
I'm not getting any code where there are containers with image backgrounds. Is it possible to this in even is the file name of the image can just be a placeholder.

**Comment by bernaferrari** [comment]
Hey, you are right. Are you talking about Tailwind, Flutter or SwiftUI? I can add a placeholder, but I can't add the image.

**Comment by michael4reynolds** [comment]
I noticed it in flutter.

**Comment by pandoratoolbox** [comment]
> Hey, you are right. Are you talking about Tailwind, Flutter or SwiftUI? I can add a placeholder, but I can't add the image.

Sounds like a good idea by the OP

**Comment by bernaferrari** [comment]
Done in https://github.com/bernaferrari/FigmaToCode/commit/22639954de289f3c85910dfddfad44ae10f48a3d !
