### ISSUE TITLE
Migrate UI bundling from rollup to webpack

### ISSUE THREAD

**Issue by burhanuday** [bernaferrari/FigmaToCode#70]
since there is now an official svelte-loader for webpack, i could take a stab at migrating the bundling to webpack 5
the advantage is that there is only one bundler to worry about

**Comment by bernaferrari** [comment]
I would love to, but I don't think I know how. Need to check if figma has updated their sample to webpack 5.

**Comment by bernaferrari** [comment]
I want to have webpack watch working with svelte

**Comment by burhanuday** [comment]
Okay. Let me take a look. I'll send a PR if i am able to get it working

**Comment by burhanuday** [comment]
@bernaferrari I have a basic version of working HMR for svelte with webpack 5. It might require some changes. Would urge you to switch to the PR and let me know whats not working
