### ISSUE TITLE
Wrong `height` value in Flutter's TextStyle

### ISSUE THREAD

**Issue by ksokolovskyi** [bernaferrari/FigmaToCode#77]
According to the Flutter documentation of the `TextStyle` class (https://api.flutter.dev/flutter/painting/TextStyle/height.html):
`height` - "The height of this text span, as a multiple of the font size."

Currently, when the user sets a `Line height` parameter of the font, the plugin just uses this value for the height of the `TextStyle`, which is wrong.

I propose to do the next:
1. `Line height unit == AUTO`: skip it in `TextStyle`;
2. `Line height unit == PIXELS`: set value as `lineHeight.value / fontSize` in `TextStyle`;
3. `Line height unit == PERCENT`: set value as `lineHeight.value / 100` in `TextStyle`.

**Comment by james-majormap** [comment]
It still shows wrong `height` value.

In my case, `font size` is 18px and `line hight` is 21.6px.
The correct height should be 1.2, but it's displaying 0.07.

![스크린샷 2024-12-11 오후 5 47 00](https://github.com/user-attachments/assets/f4a93c69-1ae7-4233-9f64-46eb617ea9fd)

I confirmed that dividing 1.2 by a font size of 18 results in 0.0666..., and I found a part of the code where the `font size` was being divided again.

I propose this:

packages/backend/src/flutter/flutterTextBuilder.ts
```
   - height: lineHeight/fontSize,
91 + height: lineHeight,

```

**Comment by bernaferrari** [comment]
Thanks. There are some things that flutter is really confusing.
