### ISSUE TITLE
Transformers Idea

### ISSUE THREAD

**Issue by 0000marcell** [bernaferrari/FigmaToCode#9]
I think that seperating the transform logic from the rest of the code is a good idea, just expose the transformed IR, and then a module with the transformation logic is called for each type of transformation, and people can contribute writing their own transformation logic, I'm working on something very similar here https://github.com/figmatools/figma2css-app, but you're way ahead of me, I already use something like that in production where I work, but I'm trying to make a nice frontend so more people can use it, If you give me the go ahead I'm gonna try to implement my transformer idea and write a transformer for vanilla css, which is what I use.
My usecase is:
I Already have the HTML structure, I just need the styles

**Comment by bernaferrari** [comment]
Hey, thanks for the issue. The problem of 'totally separating them' is that they are almost totally separated already. The only transformations that happen, happen in a few lines, like this (https://github.com/bernaferrari/FigmaToCode/blob/904d83ba5021e04f89adc35ca1d5f35f4c1f6d84/src/altNodes/altConversion.ts#L130). If I remove them from here, I would need to pass through the chain of nodes/children again after. I won't say it would be slow, but it wouldn't be efficient, and there wouldn't be any benefit of adding 20 lines to wrap two. If you want to make your own transformer, you can replace, for example, convertNodesOnRectangle, with something else.

**Comment by 0000marcell** [comment]
Thanks, I'm gonna try to just transform to css, wish me luck :smile:

**Comment by bernaferrari** [comment]
I think you are probably asking a different question. If you want to convert to CSS, it has nothing to do with the IR, you would just need to copy tailwind/flutter/swiftui directory and change the methods to do css. Tailwind should be easier since it is already css with restrictions.

**Comment by 0000marcell** [comment]
Thanks a lot, @bernaferrari, it took me some time to run the project, I know this is not related but I don't know if I should open an issue just for that, but I think you should commit the lock files, one more thing is that I think invisible object should be placed in the final conversion, the designers on my team put a lot of invisible stuff in the components to demonstrate different behaviors, I think it's a pretty common practice among designers, maybe we could have a checkbox where you choose to convert invisible elements or not

**Comment by bernaferrari** [comment]
I am committing the yarn.lock
What do you mean by invisible objects? I tried to deal with them, they shouldn't be completely out. Can you give some examples of what you want? I might be able to include it.

**Comment by 0000marcell** [comment]
https://www.figma.com/file/xQLN2DE8j5wgiD8vaVOnTX/remove-later-nl-copy, this file is an example of what i'm talking about, take a look at the input element, you see that there's quite a few of inputs hidden, designers do this to show different behavior, they use that little "eye" icon to hide and show the elements, that's what I mean by invisible, when you convert those you don't actually want to create 5 diferent inputs, actually I can't think about a situation where you want the invisible items to be created in your html file

**Comment by 0000marcell** [comment]
I've made a PR solving my issue, we can discuss it there :)
