### ISSUE TITLE
I can't find this great plugin in Figma VSCode extension

### ISSUE THREAD

**Issue by eladcandroid** [bernaferrari/FigmaToCode#93]
![Screenshot 2024-01-25 at 10 06 11](https://github.com/bernaferrari/FigmaToCode/assets/13297000/f8fbea32-c2e9-4b90-8025-8cd1de41f10f)

**Comment by bernaferrari** [comment]
That's interesting.

**Comment by bernaferrari** [comment]
There was a flag that needed to be enabled. Thanks for the heads up. Should work now!

**Comment by eladcandroid** [comment]
It works! Thanks a lot!

**Comment by mzimdars-gms-online-de** [comment]
This is really cool, thanks for this plugin.
in VSCode I am unable to find the generation options (e.g. 'embed images') that are available in figma itself. DO I miss something?

**Comment by bernaferrari** [comment]
I don't think vscode allows me to show the settings
