### ISSUE TITLE
missing identifier Stack 

### ISSUE THREAD

**Issue by mich2k** [bernaferrari/FigmaToCode#97]
<img width="843" alt="image" src="https://github.com/bernaferrari/FigmaToCode/assets/13397578/b8999f04-ff72-40b3-87d5-4a483fe4c86b">

Hello,
I was wondering how happens all the stack children are a single comma thus getting hundreds of errors

thank you!

**Comment by bernaferrari** [comment]
uh ohhhh, that's a bug! Probably caused by variants/I don't know. Can you share the figma file (or even what you are trying to export) so I can fix?

**Comment by mich2k** [comment]
Hello,
Thank you for the confirmation, I am just getting familiar with Figma and so far I was just exploring this plugin, I have tried with [this](https://www.figma.com/community/file/1353822261926863339/ui-dashboard-with-data-table) and [this](https://www.figma.com/file/RWGEB79acp4lS4S6294DR4/Speaker-App-UI-%7C%7C-Bigcrocs-(Community)?type=design&node-id=51-225&mode=design&t=2twAu8feO48rjEmO-0)

**Comment by bernaferrari** [comment]
Thanks. I’ll fix them shortly. Figma is always changing, so sometimes it is hard to cover every single corner.

**Comment by bernaferrari** [comment]
Sorry. I'll get it working until Wednesday!!

**Comment by bernaferrari** [comment]
I fixed and made the icon be a FlutterLogo. Check if you like. It is hard to deal with icons. I could make it a red square too, or just ignore. What would you prefer?
