### ISSUE TITLE
Making the plugin standalone

### ISSUE THREAD

**Issue by asmirbelkic** [bernaferrari/FigmaToCode#98]
Hi, any plan to make this plugin standalone i mean without the need of dev feature ?
Since the dev feature is missing now in free plans u absolutely need it to use this free plugin can we solve this by making this plugin a separate window in figma ?

Ty

**Comment by bernaferrari** [comment]
There is absolutely no need for dev feature and the plugin already works in
a standalone window. Just right click on the canvas, plug-ins, and find it.
